### ISSUE TITLE
Cloudflare Mainland China data is missing

### ISSUE THREAD

**Issue by wasmithee** [DavidJKTofan/sase-cloud-map#2]
Awesome site!  I see that Cloudflare data is "auto-updated", I also don't see any of the mainland China locations represented.

**Comment by DavidJKTofan** [comment]
Thank you @wasmithee !

According to Cloudflare's [DevDocs](https://developers.cloudflare.com/china-network/), _"data centers located in mainland China and operated by Cloudflare’s partner JD Cloud"_, therefore we didn't include them. However, we might include them in the near future 👍 

In the meantime, I updated README to clarify this.
